threads: 12
state_path: "E:/data/scraper/ony/state"
output_path: "E:/data/scraper/ony/"
log_level: "INFO"
persist_processed_urls: true
source_rate_limit: 50
scrape_rate_limit: 100

sources:
  - name: "gdelt"
    enabled: true
    type: "rss"
    url: "https://api.gdeltproject.org/api/v2/doc/doc?query=%s+sourcelang:eng&mode=artlist&maxrecords=250&format=rss&startdatetime=%s&enddatetime=%s"
    url_path: "link"
    period_weeks: 1
    num_periods: 256
    date_format: "20060102150405"
    scrape: true
    scrape_required_terms:
      - 'Mondelez'
    
    terms_list:
    - 'sustainability AND (labour OR economic development OR governance OR environment OR environmental damage)'