threads: 12
state_path: "C:/Users/ghuiskens/Thesis/scraperState"
output_path: "C:/Users/ghuiskens/Thesis/scraped"
log_level: "INFO"
persist_processed_urls: true
source_rate_limit: 50
scrape_rate_limit: 100

sources:
  - name: "gdelt"
    enabled: true
    type: "rss"
    url: "https://api.gdeltproject.org/api/v2/doc/doc?query=%s+sourcelang:eng&mode=artlist&maxrecords=250&format=rss&startdatetime=%s&enddatetime=%s"
    url_path: "link"
    period_weeks: 1
    num_periods: 52
    date_format: "20060102150405"
    scrape: true
    scrape_required_terms:
      - 'diabetes'
    terms_list:
      - 'diabetes AND (funding OR financing OR licencing OR merger OR acquisition OR venture OR investment OR "clinical trial")'