threads: 12
state_path: "E:/data/scraper/kyc/state"
output_path: "E:/data/scraper/kyc/"
log_level: "INFO"
persist_processed_urls: true
source_rate_limit: 5000
scrape_rate_limit: 10

sources:
  - name: "gdelt"
    enabled: true
    type: "rss"
    url: "https://api.gdeltproject.org/api/v2/doc/doc?query=%s+sourcelang:eng&mode=artlist&maxrecords=250&format=rss&startdatetime=%s&enddatetime=%s"
    url_path: "link"
    period_weeks: 4
    num_periods: 60
    date_format: "20060102150405"
    scrape: true
    scrape_required_terms:
      - 'kyc'
    terms_list:
      - '(KYC OR "know your customer" OR CDD OR "customer due diligence") AND (ING OR "abn amro" OR rabobank OR robeco OR "van lanschot" OR kempen OR volksbank)'
      - '(KYC OR "know your customer" OR CDD OR "customer due diligence") AND (quantexa OR fenurgo OR "delta capita" OR "efficient frontiers")'
      - '(KYC OR "know your customer" OR CDD OR "customer due diligence") AND (netherlands OR dutch)'

  - name: "google news"
    enabled: true
    type: "rss"
    url: "https://news.google.com/rss/search?q=%s+after:%s+before:%s"
    url_path: "link"
    period_weeks: 4
    num_periods: 60
    date_format: "2006-01-02"
    scrape: true
    scrape_required_terms:
      - 'kyc'
    terms_list:
      - '(KYC OR "know your customer" OR CDD OR "customer due diligence") AND (ING OR "abn amro" OR rabobank OR robeco OR "van lanschot" OR kempen OR volksbank)'
      - '(KYC OR "know your customer" OR CDD OR "customer due diligence") AND (quantexa OR fenurgo OR "delta capita" OR "efficient frontiers")'
      - '(KYC OR "know your customer" OR CDD OR "customer due diligence") AND (netherlands OR dutch)'