threads: 12
state_path: "E:/data/scraper/ony/state"
output_path: "E:/data/scraper/ony/"
log_level: "INFO"
persist_processed_urls: true
source_rate_limit: 50
scrape_rate_limit: 100

sources:
  - name: "gdelt"
    enabled: true
    type: "rss"
    url: "https://api.gdeltproject.org/api/v2/doc/doc?query=%s+sourcelang:eng&mode=artlist&maxrecords=250&format=rss&startdatetime=%s&enddatetime=%s"
    url_path: "link"
    period_weeks: 1
    num_periods: 256
    date_format: "20060102150405"
    scrape: true
    scrape_required_terms:
      - 'onychomycosis'
      - 'nanomedicine'
      - 'atopic dermatitis'
      - 'tinea'
      - 'terbinafine'
      - 'tacrolimus'
      - 'phmb'
      - 'dermatophy'
      - 'cutaneous'
      - 'acne'
    terms_list:
      - '(onychomycosis OR nanomedicine OR "atopic dermatitis" OR tinea OR terbinafine) AND (funding OR financing OR licencing OR merger OR acquisition OR venture OR investment OR "clinical trial")'
      - '(tacrolimus OR PHMB OR dermatophytes OR cutaneous OR acne) AND (funding OR financing OR licencing OR merger OR acquisition OR venture OR investment OR "clinical trial")'

  - name: "google news"
    enabled: true
    type: "rss"
    url: "https://news.google.com/rss/search?q=%s+after:%s+before:%s"
    url_path: "link"
    period_weeks: 1
    num_periods: 256
    date_format: "2006-01-02"
    scrape: true
    scrape_required_terms:
      - 'onychomycosis'
      - 'nanomedicine'
      - 'atopic dermatitis'
      - 'tinea'
      - 'terbinafine'
      - 'tacrolimus'
      - 'PHMB'
      - 'dermatophy'
      - 'cutaneous'
      - 'acne'
    terms_list:
      - '(onychomycosis OR nanomedicine OR "atopic dermatitis" OR tinea OR terbinafine) AND (funding OR financing OR licencing OR merger OR acquisition OR venture OR investment OR "clinical trial")'
      - '(tacrolimus OR PHMB OR dermatophytes OR cutaneous OR acne) AND (funding OR financing OR licencing OR merger OR acquisition OR venture OR investment OR "clinical trial")'

  - name: "clinicaltrials.gov"
    enabled: true
    type: "json"
    url: "https://clinicalTrials.gov/api/query/study_fields?expr=%s&fmt=JSON&min_rnk=%d&max_rnk=%d&fields=NCTId,BriefTitle,OfficialTitle,BriefSummary,DetailedDescription,StudyFirstSubmitDate,PrimaryCompletionDate,CompletionDate,OrgFullName,LeadSponsorName,CollaboratorName,ResponsiblePartyInvestigatorFullName,OverallOfficialName,Condition,InterventionArmGroupLabel,ReferencePMID,ReferenceCitation"
    paginate: 1000
    paginate_type: "max"
    start_index: 1
    json_path: "StudyFieldsResponse.StudyFields"
    url_path: "NCTId.0"
    url_prefix: "https://clinicaltrials.gov/ct2/show/"
    title_path: "OfficialTitle.0"
    text_path: "DetailedDescription.0"
    terms_list:
      - 'onychomycosis'
      - 'nanomedicine'
      - '"atopic dermatitis"'
      - 'tinea'
      - 'terbinafine'
      - 'tacrolimus'
      - 'PHMB'
      - 'dermatophytes'
      - 'cutaneous'
      - 'acne'


  - name: "clinicaltrialsregister.eu"
    enabled: true
    type: "rss"
    url: "https://www.clinicaltrialsregister.eu/ctr-search/rest/feed/bydates?query=%s&dateFrom=%s&dateTo=%s"
    url_path: "link"
    text_path: "description"
    period_weeks: 52
    num_periods: 10
    date_format: "2006-01-02"
    terms_list:
      - 'onychomycosis'
      - 'nanomedicine'
      - 'atopic+dermatitis'
      - 'tinea'
      - 'terbinafine'
      - 'tacrolimus'
      - 'PHMB'
      - 'dermatophytes'
      - 'cutaneous'
      - 'acne'

  - name: "semantic scholar"
    enabled: true
    type: "json"
    url: "https://api.semanticscholar.org/graph/v1/paper/search?query=%s&offset=%d&limit=%d&fields=externalIds,url,title,abstract,year,fieldsOfStudy"
    api_key: "hhpOaNZ8kb4XjhxZGUj284CQmJVYYKJk4ePPjXlq"
    json_path: "data"
    url_path: "url"
    text_path: "abstract"
    secondary_url: "https://api.semanticscholar.org/graph/v1/paper/%s?fields=tldr,authors.externalIds,authors.url,authors.name,authors.affiliations,authors.homepage,citations.paperId,citations.title,citations.url,citations.year,references.paperId,references.title,references.url,references.year"
    join_field: "paperId"
    paginate: 100
    paginate_type: "limit"
    start_index: 0
    terms_list:
      - 'onychomycosis'
