threads: 12
state_path: "E:/data/scraper/demo/state"
output_path: "E:/data/scraper/torzi"
log_level: "INFO"
persist_processed_urls: false
source_rate_limit: 5000
scrape_rate_limit: 10

sources:
#  - name: "gdelt"
#    enabled: true
#    type: "rss"
#    url: "https://api.gdeltproject.org/api/v2/doc/doc?query=%s+sourcelang:eng&mode=artlist&maxrecords=250&format=rss&startdatetime=%s&enddatetime=%s"
#    url_path: "link"
#    period_weeks: 4
#    num_periods: 6
#    date_format: "20060102150405"
#    scrape: true
#    scrape_required_terms:
#      - 'adam fox'
#    terms_list:
#      - '"adam fox"'

  - name: "google news"
    enabled: true
    type: "rss"
    url: "https://news.google.com/rss/search?q=%s+after:%s+before:%s"
    url_path: "link"
    period_weeks: 1
    num_periods: 52
    date_format: "2006-01-02"
    scrape: true
    scrape_required_terms:
      - 'gianluigi torzi'
    terms_list:
      - 'gianluigi torzi'
